// Correct way to import local fonts in Next.js 13
import localFont from "next/font/local";
import "./globals.css";

// Use localFont to load custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff", // Ensure fonts are placed in the public folder
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff", // Ensure fonts are placed in the public folder
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for your app
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
